name = "boolubtravel-marketing-backend"
main = "backend/worker.js"
compatibility_date = "2024-03-01"

[vars]
NODE_ENV = "production"

[[kv_namespaces]]
binding = "BOOLUB_DB"
id = "7001e5e22f82477dac13082abf008494"
